# hydra:
#   run:
#     dir: /mnt/maara/singapore_project/hydra/

wandb:
  project: vine-9001
  entity: harry1576
  mode: online
  dir: /local/smart-tree/

fp16: True
num_epoch: 200
lr_decay: True
lr: 0.005
early_stop_epoch: 20
early_stop: True

batch_size: 8
directory: /local/synthetic-vine-pcds-3-rotated
json_path: /local/smart-tree/smart_tree/conf/vines/vine-split-synthetic.json
voxel_size: 0.005
input_feature_names : ['xyz']
target_feature_names: ['class_l']

cmap:
    - [1.0, 0.0, 0.0] # Trunk
    - [0.0, 1.0, 0.0] # Spur / Cane / Shoot
    - [0.0, 0.0, 1.0] # Node
    - [1.0, 1.0, 0.0] # Wire
    - [0.0, 1.0, 1.0] # Post
    - [1.0, 0.5, 1.0] # Noise

########################################
# Training Dataset
########################################
train_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: train
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  augmentation:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations:
      - _target_: smart_tree.dataset.augmentations.LabelDropout
        probability: 0.99

      # - _target_: smart_tree.dataset.augmentations.CentreCloud
      # # - _target_: smart_tree.dataset.augmentations.RemoveGround
      # #   ground_height: 0.4


  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    target_feature_names: ${target_feature_names}
    voxel_size: ${voxel_size}

train_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: True
  pin_memory: False
  num_workers: 0
  shuffle: True

  # sampler:
  #   _target_: torch.utils.data.RandomSampler
  #   replacement: true
  #   num_samples: 128
  #   data_source: ${train_dataset}

  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  dataset: ${train_dataset}

########################################
# Validation Dataset
########################################
validation_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: validation
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    target_feature_names: ${target_feature_names}
    voxel_size: ${voxel_size}

validation_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  dataset: ${validation_dataset}

########################################
# Test Dataset
########################################
test_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: test
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    target_feature_names: ${target_feature_names}
    voxel_size: ${voxel_size}

test_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  dataset: ${test_dataset}

########################################
# Capture Dataset / Settings
########################################
capture_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: capture
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    voxel_size: ${voxel_size}
    extract_point_ids: False
    extract_masks: False

  augmentation:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations:
      - _target_: smart_tree.dataset.augmentations.CentreCloud


capture_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  # sampler:
  #   _target_: torch.utils.data.RandomSampler
  #   replacement: True
  #   num_samples: 8
  #   data_source: ${capture_dataset}

  dataset: ${capture_dataset}

capture_output: False
capture_on_improvement: True
capture_final_epoch: False
capture_epoch: 5
capture_delete_old_artifacts: True
capture_fn:
  _target_: smart_tree.model.sparse.helper.model_output_to_labelled_clds
  _partial_: True
  cmap: ${cmap}


model:
  _target_: smart_tree.model.sparse.model.Smart_Tree
  input_channels: 3
  unet_planes: [32, 64, 128, 256, 384, 384, 512, 512]
  mlp_layers: 3
  num_classes: 6
  target_features: ${target_feature_names}

optimizer:
  _target_: torch.optim.Adam
  lr: ${lr}

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: "min"

training_tracker:
  _target_: smart_tree.model.tracker.SegmentationTracker

val_tracker:
  _target_: smart_tree.model.tracker.SegmentationTracker

test_tracker:
  _target_: smart_tree.model.tracker.SegmentationTracker
