pipeline:
  _target_: smart_tree.pipeline.Pipeline
  
  preprocessing:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations: 
      - _target_:  smart_tree.dataset.augmentations.CentreCloud
      - _target_:  smart_tree.dataset.augmentations.Scale
        min_scale: 10
        max_scale: 10


  model_inference: 
    _target_: smart_tree.model.model_inference.ModelInference
    model:
      _target_: smart_tree.model.model_inference.load_model
      model_path:  /local/smart-tree/smart_tree/model/weights/peach-forest-65_model.pt
      weights_path: /local/smart-tree/smart_tree/model/weights/peach-forest-65_model_weights.pt
    
    dataloader:
      _target_: smart_tree.model.model_inference.load_dataloader
      _partial_: True
      block_size: 4.0
      buffer_size: 0.4
      num_workers: 0
      batch_size: 4
      
      transform:
        _target_ : smart_tree.model.transform.sparse_voxelize
        _partial_ : True
        use_xyz: True
        use_rgb: False
        voxel_size: 0.01
        fp_16: False
      
      collate_fn:
        _target_: smart_tree.model.util.batch_collate
        _partial_: True




  skeletonizer:
    _target_: smart_tree.skeleton.skeletonize.Skeletonizer
    K: 16
    min_connection_length: 0.01
    minimum_graph_vertices: 32
    repair_skeletons : True
    smooth_skeletons : True
    smooth_kernel_size: 11 #Needs to be odd
    prune_skeletons : True
    min_skeleton_radius : 0.01
    min_skeleton_length : 0.02

  view_model_output : False
  view_skeletons : True
  save_path: /
  save_outputs : False
  
  branch_classes: [0]
  cmap:
    - [0.450, 0.325, 0.164] # Trunk
    - [0.541, 0.670, 0.164] # Foliage