pipeline:
  _target_: smart_tree.pipeline.Pipeline
  
  preprocessing:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations: 
      - _target_:  smart_tree.dataset.augmentations.CentreCloud


  model_inference: 
    _target_: smart_tree.model.model_inference.ModelInference

    model:
      _target_: smart_tree.util.file.load_model
      model_path: smart_tree/model/weights/noble-elevator-58_model.pt
      weights_path: smart_tree/model/weights/noble-elevator-58_model_weights.pt

    dataloader:
      _target_: torch.utils.data.DataLoader
      _partial_: True
      batch_size: 4
      num_workers: 4
      collate_fn:
        _target_: smart_tree.model.collate.inference_collate
        _partial_: True


    dataset:
      _target_: smart_tree.dataset.dataset.SingleTreeInference
      _partial_: True
      block_size: 4
      buffer_size: 0.4
      min_points: 20
      voxelizer:
        _target_: smart_tree.model.voxelize.SparseVoxelizer
        voxel_size: 0.01
        use_xyz: True
        use_rgb: False
        voxelize_radius: False
        voxelize_direction: False
        voxelize_class: False
        voxelize_mask: True
        min_xyz: [0,0,0]
        max_xyz: [4.8,4.8,4.8] # block + (buffer * 2)
        max_num_voxels: 5000000



  skeletonizer:
    _target_: smart_tree.skeleton.skeletonize.Skeletonizer
    K: 16
    min_connection_length: 0.02 
    minimum_graph_vertices: 32

  view_model_output : False
  view_skeletons : False
  save_path: /
  save_outputs : False
  
  branch_classes: [0]
  cmap:
    - [0.450, 0.325, 0.164] # Trunk
    - [0.541, 0.670, 0.164] # Foliage

  repair_skeletons : True
  smooth_skeletons : True
  smooth_kernel_size: 11 # Needs to be odd
  prune_skeletons : True 
  min_skeleton_radius : 0.01 
  min_skeleton_length : 0.02

