pipeline:
  _target_: smart_tree.pipeline.Pipeline

  preprocessing:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations:
      - _target_:  smart_tree.dataset.augmentations.CentreCloud
#      - _target_:  smart_tree.dataset.augmentations.Scale
#        min_scale: 0.5
#        max_scale: 0.5
#      - _target_:  smart_tree.dataset.augmentations.FixedRotate
#        xyz: [1.57, 0.0, 0.0]

  model_inference:
    _target_: smart_tree.model.model_inference.ModelInference

    model:
      _target_: smart_tree.model.model_inference.load_model
      model_path: /local/smart-tree/outputs/2023-09-20/12-36-34/dandy-lion-53_model.pt
      weights_path: /local/smart-tree/outputs/2023-09-20/12-36-34/dandy-lion-53_model_weights.pt

    dataloader:
      _target_: smart_tree.model.model_inference.load_dataloader
      _partial_: True
      block_size: 4.0
      buffer_size: 0.4
      num_workers: 0
      batch_size: 4
      transform:
        _target_: smart_tree.model.sparse.transform.sparse_voxelize
        _partial_: True
        voxel_size: 0.01
        input_features: ['xyz']
      collate_fn:
        _target_: smart_tree.model.sparse.util.batch_collate
        _partial_: True

  skeletonizer:
    _target_: smart_tree.skeleton.skeletonize.Skeletonizer
    K: 8
    min_connection_length: 0.04
    minimum_graph_vertices: 12

    repair_skeletons : True
    smooth_skeletons : False
    smooth_kernel_size: 11 # Needs to be odd
    prune_skeletons : False
    min_skeleton_radius : 0.01
    min_skeleton_length : 0.02


  view_model_output : True
  view_skeletons : True
  save_path: /mnt/harry/PhD/smart-tree/data/wtf
  save_outputs : True
  branch_classes: [0,1]
  cmap:
    - [0.541, 0.670, 0.164] # Foliage
    - [0.450, 0.325, 0.164] # Trunk
