# @package: _global_

run:
  dir: ./outputs

wandb:
  project: tree
  entity: harry1576
  mode: disabled 

fp16: True
num_epoch: 5000
lr_decay: True
lr: 0.001
early_stop_epoch: 20
early_stop: True

batch_size: 8
directory: /local/smart-tree/data/branches
json_path: smart_tree/conf/training-split.json
blocking: True
block_size: 4
buffer_size: 0.4
voxel_size: 0.01


capture_output: 1

input_features:
  - xyz

target_features:
  - radius
  - direction
  - class_l


train_dataset:
  _target_: smart_tree.dataset.dataset.TreeDataset
  mode: train
  voxel_size: ${voxel_size}
  directory: ${directory}
  json_path: ${json_path}
  blocking: ${blocking}
  block_size: ${block_size}
  buffer_size: ${buffer_size}
  input_features: ${input_features}
  target_features: ${target_features}

test_dataset:
  _target_: smart_tree.dataset.dataset.TreeDataset
  mode: test
  voxel_size: ${voxel_size}
  directory: ${directory}
  json_path: ${json_path}
  blocking: ${blocking}
  block_size: ${block_size}
  buffer_size: ${buffer_size}
  input_features: ${input_features}
  target_features: ${target_features}

validation_dataset:
  _target_: smart_tree.dataset.dataset.TreeDataset
  mode: validation
  voxel_size: ${voxel_size}
  directory: ${directory}
  json_path: ${json_path}
  blocking: ${blocking}
  block_size: ${block_size}
  buffer_size: ${buffer_size}
  input_features: ${input_features}
  target_features: ${target_features}

train_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  # sampler:
  #   _target_: torch.utils.data.RandomSampler
  #   replacement: True
  #   num_samples: 1024
  #   data_source: ${train_dataset}
  collate_fn:
    _target_: smart_tree.model.sparse.batch_collate
    _partial_: True
  dataset: ${train_dataset}

validation_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.batch_collate
    _partial_: True
  dataset: ${validation_dataset}


test_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.batch_collate
    _partial_: True
  dataset: ${test_dataset}


model:
  _target_: smart_tree.model.model.Smart_Tree
  input_channels: 3
  unet_planes: [8, 16, 32, 64]
  radius_fc_planes: [8, 8, 4, 1]
  direction_fc_planes: [8, 8, 4, 3]
  class_fc_planes: [8, 8, 4, 2] 

optimizer:
  _target_: torch.optim.Adam 
  lr: ${lr}


scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: "min"