# hydra:
#   run:
#     dir: /mnt/maara/singapore_project/hydra/

wandb:
  project: vine-9001
  entity: harry1576
  mode: online
  dir: /local/smart-tree

fp16: True
num_epoch: 200
lr_decay: True
lr: 0.005
early_stop_epoch: 20
early_stop: True

batch_size: 1
directory: /mnt/harry/PhD/smart-tree/data/synthetic-vine-pcds-3-rotated
json_path: /mnt/harry/PhD/smart-tree/smart_tree/conf/vines/vine-split.json
voxel_size: 0.005
input_feature_names : ['xyz']
target_feature_names: ['class_l']

cmap:
    - [1.0, 0.0, 0.0] # Trunk
    - [0.0, 1.0, 0.0] # Spur / Cane / Shoot
    - [0.0, 0.0, 1.0] # Node
    - [1.0, 1.0, 0.0] # Wire
    - [0.0, 1.0, 1.0] # Post
    - [1.0, 0.5, 1.0]
    - [0.0, 0.5, 1.0]


########################################
# Training Dataset
########################################
train_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: train
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  augmentation:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations:
      - _target_: smart_tree.dataset.augmentations.CentreCloud
      - _target_: smart_tree.dataset.augmentations.LabelDropout
        probability: 0.99
      # # # - _target_: smart_tree.dataset.augmentations.RemoveGround
      # # #   ground_height: 0.4
      - _target_: smart_tree.dataset.augmentations.RandomFlips
        x_prob: 0.5
        y_prob: 0.5
      - _target_: smart_tree.dataset.augmentations.RandomAugmentation
        shuffle: true
        apply_prob: 0.5
        augmentations:
          - _target_: smart_tree.dataset.augmentations.SaltNoise
            percentage: 0.005  # based on number of xyz points add random points
            label_id: 5
          - _target_: smart_tree.dataset.augmentations.RandomGaussianPeturb
            mean: 0.0
            std: 1.0
            prob: 0.75
            magnitude: 0.002
          - _target_: smart_tree.dataset.augmentations.RandomRotate
            max_x: 0.5
            max_y: 0.5
            max_z: 0.5
          - _target_: smart_tree.dataset.augmentations.Scale
            min_scale: 0.75
            max_scale: 1.2
          - _target_: smart_tree.dataset.augmentations.RandomTranslate
            max_x: 2.0
            max_y: 2.0
            max_z: 2.0
          # - _target_: smart_tree.dataset.augmentations.RandomCrop
          #   max_x: 0.8
          #   max_y: 0.4
          #   max_z: 0.8
          - _target_: smart_tree.dataset.augmentations.Dropout3D
            noise_scale:
            - 0.4
            - 1.2
            octaves: 6
            freq_multiplier: 1.2
            dropout:
            - 0.0
            - 0.3
            peturb:
            - 0.1
            - 0.4
            peturb_bias: 0.5
            peturb_distance:
            - 0.0
            - 0.008

  # transform:
  #   _target_ : smart_tree.model.sparse.transform.sparse_voxelize
  #   _partial_ : True
  #   input_feature_names: ${input_feature_names}
  #   target_feature_names: ${target_feature_names}
  #   voxel_size: ${voxel_size}

train_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: True
  pin_memory: False
  num_workers: 0
  shuffle: True

  collate_fn:
    _target_: smart_tree.model.helper.identity_collate_fn
    _partial_: True

  dataset: ${train_dataset}

########################################
# Validation Dataset
########################################
validation_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: validation
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    target_feature_names: ${target_feature_names}
    voxel_size: ${voxel_size}

validation_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  dataset: ${validation_dataset}

########################################
# Test Dataset
########################################
test_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: test
  directory: ${directory}
  json_path: ${json_path}
  cache: True
  transform:
    _target_ : smart_tree.model.sparse.transform.sparse_voxelize
    _partial_ : True
    input_feature_names: ${input_feature_names}
    target_feature_names: ${target_feature_names}
    voxel_size: ${voxel_size}

test_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: False
  pin_memory: False
  num_workers: 0
  shuffle: False
  collate_fn:
    _target_: smart_tree.model.sparse.util.batch_collate
    _partial_: True
    fp_16: ${fp16}

  dataset: ${test_dataset}

########################################
# Capture Dataset / Settings
########################################
capture_dataset:
  _target_: smart_tree.dataset.dataset.Dataset
  mode: capture
  directory: ${directory}
  json_path: ${json_path}
  cache: True

  augmentation:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations:
        - _target_: smart_tree.dataset.augmentations.CentreCloud


capture_data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  drop_last: True
  pin_memory: False
  num_workers: 0
  shuffle: True

  collate_fn:
    _target_: smart_tree.model.helper.identity_collate_fn
    _partial_: True

  dataset: ${capture_dataset}
